version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgre
    command: /backend/entrypoint.sh
    volumes:
      - ./backend:/backend
  postgre:
    container_name: postgre
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    restart: unless-stopped
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/backend/static

    depends_on:
      - backend
      - frontend
volumes:
  db-data:
  node_modules:
  static:
