# Generated by Django 4.2.8 on 2024-01-20 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('TextContentId', models.IntegerField(primary_key=True, serialize=False)),
                ('OriginalText', models.CharField(max_length=200)),
                ('LanguageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.languages')),
            ],
        ),
    ]
