//-------auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const LOAD_USER = "LOAD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const CLEAN_AUTH = "CLEAN_AUTH";

//------Languages
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

//------THEME
export const CHANGE_THEME = "CHANGE_THEME";

//--------SIGNUP
export const SIGNUP_UPDATE_VALUE = "SIGNUP_UPDATE_VALUE";
export const SIGNUP_SET_ERROR = "SIGNUP_SET_ERROR";
export const CLEAN_SIGNUP_FORM = "CLEAN_SIGNUP_FORM";

//--------LOGIN
export const LOGIN_UPDATE_VALUE = "LOGIN_UPDATE_VALUE";
export const LOGIN_SET_ERROR = "LOGIN_SET_ERROR";
export const CLEAN_LOGIN_FORM = "CLEAN_LOGIN_FORM";

//------Notification
export const CHANGE_NOTIFICATION = "CHANGE_NOTIFICATION";

//-----------CHAT
export const UPDATE_CHAT_LIST = "UPDATE_CHAT_LIST";
export const CHANGE_SELECTED_CHAT = "CHANGE_SELECTED_CHAT";
export const REFRESH_CHAT = "REFRESH_CHAT";

//---------BLOG
export const BLOG_UPDATE_VALUE = "BLOG_UPDATE_VALUE";
export const BLOG_SET_ERROR = "BLOG_SET_ERROR";
export const CHANGE_BLOG_PAGE = "CHANGE_BLOG_PAGE";

//--------CHANGE_PASS
export const CHANGEPASSWORD_UPDATE_VALUE = "CHANGEPASSWORD_UPDATE_VALUE";
export const CHANGEPASSWORD_SET_ERROR = "CHANGEPASSWORD_SET_ERROR";
export const CLEAN_CHANGEPASSWORD_FORM = "CLEAN_CHANGEPASSWORD_FORM";

//--------About
export const ABOUT_UPDATE_VALUE = "ABOUT_UPDATE_VALUE";
export const ABOUT_SET_ERROR = "ABOUT_SET_ERROR";
export const CLEAN_ABOUT_FORM = "CLEAN_ABOUT_FORM";

//--------LOGIN
export const PERSONALINFO_UPDATE_VALUE = "PERSONALINFO_UPDATE_VALUE";
export const PERSONALINFO_SET_ERROR = "PERSONALINFO_SET_ERROR";
export const CLEAN_PERSONALINFO_FORM = "CLEAN_PERSONALINFO_FORM";
export const PERSONALINFO_FILL_VALUE = "PERSONALINFO_FILL_VALUE";

//--------KnownSkills
export const KNOWNSKILLS_UPDATE_VALUE = "KNOWNSKILLS_UPDATE_VALUE";
export const KNOWNSKILLS_SET_ERROR = "KNOWNSKILLS_SET_ERROR";
export const CLEAN_KNOWNSKILLS_FORM = "CLEAN_KNOWNSKILLS_FORM";

//--------UnKnownSkills
export const UNKNOWNSKILLS_UPDATE_VALUE = "UNKNOWNSKILLS_UPDATE_VALUE";
export const UNKNOWNSKILLS_SET_ERROR = "UNKNOWNSKILLS_SET_ERROR";
export const CLEAN_UNKNOWNSKILLS_FORM = "CLEAN_UNKNOWNSKILLS_FORM";
