# Generated by Django 4.2.8 on 2024-01-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TextContent', '0001_initial'),
        ('Languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Translations', models.CharField(max_length=200)),
                ('LanguageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Languages.languages')),
                ('TextContentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextContent.textcontent')),
            ],
        ),
    ]
