# Generated by Django 4.2.8 on 2024-01-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('LanguageId', models.CharField(primary_key=True, serialize=False)),
                ('LanguageCode', models.CharField(max_length=5)),
                ('LanguageName', models.CharField(max_length=100)),
            ],
        ),
    ]
